# Generated by Django 5.0.2 on 2024-02-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='t_yil',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
